<a href="https://colab.research.google.com/github/AmmarSahyoun/Colab_Coursera/blob/master/LIST_vs_Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
L = [1,2,3]
L

[1, 2, 3]

In [ ]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [ ]:
for i  in L:
  print(i)

1
2
3


In [ ]:
for i in A:
  print(i)

1
2
3


In [ ]:
L.append(4)
L

[1, 2, 3, 4]

In [ ]:
L = L+['w']
L

[1, 2, 3, 4, 'w']

In [ ]:
A = A +[4]
A

array([5, 6, 7])

## The + with List does concatenation, The + with numpyarray does vector addition

In [ ]:
2*A #scalar multiply by vector

array([10, 12, 14])

In [ ]:
2*L # to make multiply for each elemnt use for loop

[1, 2, 3, 4, 'w', 1, 2, 3, 4, 'w']

In [ ]:
A

array([5, 6, 7])

In [ ]:
np.sqrt(A)

array([2.23606798, 2.44948974, 2.64575131])

In [ ]:
np.log(A)

array([1.60943791, 1.79175947, 1.94591015])

In [ ]:
np.exp(A)

array([ 148.4131591 ,  403.42879349, 1096.63315843])

## numpy allows to treat array like a vector, a mathematical object to do operations

## To do mathematical operations on  list we need to for loop in each element, but for loop in python are very slow. SO it is better to use numpy array for mathematical operation