<a href="https://colab.research.google.com/github/AmmarSahyoun/Colab_Coursera/blob/master/Matrices_vs_Vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix is a two dimensional np.array, it is a list of list, Vector is one dimentional np.array, matrix is 2D vectors

In [4]:
import numpy as np
m = np.array([[1,2], [3,4]])

In [5]:
l = [ [1,2], [3,4] ]

In [6]:
l[0][1]

2

In [7]:
m2 = np.matrix([ [1,2], [3,4] ])
m2

matrix([[1, 2],
        [3, 4]])

In [9]:
A = np.array(m2)   # transform matrix to np.array
A.T  # transpose of A 

array([[1, 3],
       [2, 4]])

### Create array, matrix

In [11]:
z = np.zeros(10); z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
z = np.zeros((10, 10)); z
# is a tuple containing each dimension

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
r = np.random.random((10,10)) ; r
# values between 0-1 cause they came from the probability to create distributed random number

array([[0.29760963, 0.74700898, 0.48414096, 0.49026884, 0.25986745,
        0.71587389, 0.77636427, 0.36607471, 0.07562109, 0.24834825],
       [0.74223047, 0.32959229, 0.68658279, 0.29031028, 0.38337523,
        0.59409938, 0.29984267, 0.97349738, 0.65309925, 0.08550524],
       [0.12100438, 0.6636942 , 0.70595921, 0.81556007, 0.77711322,
        0.09025561, 0.04015986, 0.52928953, 0.19263458, 0.52986441],
       [0.05536445, 0.51035762, 0.73442481, 0.70416864, 0.41777539,
        0.14874676, 0.04187971, 0.52728658, 0.08995744, 0.23874185],
       [0.46764621, 0.08311032, 0.42538305, 0.35398947, 0.1493206 ,
        0.97856682, 0.38374316, 0.17994521, 0.47904788, 0.84515639],
       [0.87999382, 0.2453029 , 0.24739338, 0.89736798, 0.58686477,
        0.20560546, 0.95686402, 0.6221208 , 0.44966322, 0.2754114 ],
       [0.24350411, 0.61787491, 0.13349951, 0.0417408 , 0.66243406,
        0.50390235, 0.00466661, 0.02687231, 0.94652276, 0.58330235],
       [0.89074675, 0.82996766, 0.3530869

In [18]:
# Create Gaussian distributed number with mean 0 and variance 1
g = np.random.randn(10, 10) ; g

array([[ 0.92017642, -0.41472505, -0.49974854,  0.13448255, -0.12017084,
         0.0828378 , -0.32456597,  2.18921137,  0.72495358, -1.32774051],
       [ 0.43028889,  1.49355277, -2.07799276,  0.77524702,  0.8657803 ,
        -1.21524   , -0.42654632,  1.56343698, -0.15502827,  0.54458409],
       [ 0.08178009, -0.12319659, -1.8123911 , -0.44105611,  0.72729541,
        -0.19616182, -0.15496084,  1.46042744,  0.75367586,  0.02291828],
       [-2.0959068 ,  1.29541258, -1.44892286,  1.62086248, -1.46705926,
        -0.45510203, -0.73750158, -0.80795694,  0.86912614, -1.66281165],
       [-0.92695552,  1.89570101, -0.68367537, -0.21136911, -0.5578835 ,
         0.41852439,  1.72399374,  0.64156141, -0.63623785, -0.02012449],
       [ 1.52643999, -1.16850641, -0.88808545, -0.57589252, -0.24721094,
         0.29094204,  1.10024455, -0.06005805, -0.10832369,  1.53849525],
       [ 0.4661611 ,  0.86828327, -0.60194248, -0.32089708, -0.91158167,
        -0.1129167 , -1.46916337, -1.44815699

In [21]:
print("the mean is: ",g.mean()) ; g.var() # variance

the mean is:  -0.09447353765115653


0.9516938512056309

## the asterisk* means element * element, but the dot means matrix * matrix

In [22]:
m = np.array([[1,2],[3,4]]) ; m

array([[1, 2],
       [3, 4]])

In [23]:
minv = np.linalg.inv(m) ; minv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
minv.dot(m)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [28]:
# the outer is the multiply product
a = np.array([1,2]) ; b= np.array([3,4]) ; np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [29]:
# the inner is the dot product
print(np.inner(a, b))
a.dot(b)

11


11

In [33]:
#matric trace is the sum of diagonal vectorr
d = np.diag(a) ; print(d) ; d.sum()

[[1 0]
 [0 2]]
3


In [34]:
print(np.trace(d))

3
